### ISSUE TITLE
特地前来感谢，个人认为是文本对抗领域的开山之作之一

### ISSUE THREAD

**Issue by cwb96** [jind11/TextFooler#10]
感谢各位！

另外，https://github.com/wqj111186/TextFooler 和 https://github.com/thunlp/TAADpapers 是否有些overlap？

**Comment by jind11** [comment]
Thanks for the overpraise. Between the two links you wrote there, the latter one is just a list of the majority of papers in this area and the former one involves some personal learning notes. They may have some overlap, which I think is ok.
