### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by jxmorris12** [jind11/TextFooler#19]
Can you post your successful examples? Would be really helpful to be able to analyze them on MR, Yelp, IMDB, SNLI, MNLI datasets. Thanks!

**Comment by jind11** [comment]
Hi, I just now uploaded our adversary results for all models and datasets: https://drive.google.com/open?id=1V8CJhrvqfeoYNZ5ov4HBE6Vq1e-MFkYy. Enjoy!
