### ISSUE TITLE
 The counter-fitting word embeddings

### ISSUE THREAD

**Issue by Palipoor** [jind11/TextFooler#21]
Hi,
This is more of a question than a real issue. I'm trying to attack a model with your code but I'm not sure what "the counter-fitting word embeddings" file should be like. Can you give an example?
Thanks

**Comment by jind11** [comment]
hi, the format of the "counter-fitting word embeddings" is the same as a normal "word embedding", where in each line, there is a token followed by many float numbers.

**Comment by Palipoor** [comment]
Thanks!
