### ISSUE TITLE
About Data Size

### ISSUE THREAD

**Issue by CuiMingyu** [jind11/TextFooler#26]
Hi, I have a question that if I have 10, 000 samples how can I change all the samples not part of samples.

I used BERT to produce adversaries samples for 10, 000 samples. But I found only part of them were changed. It seemed that the program randomly selected samples from dataset not selected all the samples.

How can I change 10, 000 samples? 

Thank you for your time!

**Comment by jind11** [comment]
The code now only changes those samples that have correct predictions and skip the wrong predictions, which is why only part of them were changed. If the BERT model has a high accuracy, then the majority of them will be changed.

**Comment by CuiMingyu** [comment]
I see. I notice the code.

Thank you for your reminder!
