### ISSUE TITLE
Implementation on other dataset

### ISSUE THREAD

**Issue by ShuangNYU** [jind11/TextFooler#29]
Hi! I want to implement TextFooler on other data set, and I have a pretrained classifier with bert model `pytorch_model.bin`. I created a new folder in a directory and used it as `--target_model_path`. In this folder I put `bert_config.json` in, but I wonder if `vocal.txt` is the same for all pretrained models. For example, can I use the `bert-base-uncased-vocal.txt` directly?

**Comment by jind11** [comment]
I am sorry but do you still have this question?

**Comment by ShuangNYU** [comment]
> I am sorry but do you still have this question?

Thanks! I set the `vocal.txt` as above, and the results make sense, so I think it works.
