### ISSUE TITLE
Not able to run cos_sim.py

### ISSUE THREAD

**Issue by ashwani-bhat** [jind11/TextFooler#30]
Hi.
I am trying to run comp_cos_sim_mat.py on the counter-fitted-vectors but I run into memory issues.
Is there any memory limit on that. I'm using google colab 12GB RAM.

**Comment by jind11** [comment]
So sorry for the late response. The cosine similarity score matrix takes about 30 GB of RAM, so 12 GB RAM is not enough and will cause the out of memory problem.
