### ISSUE TITLE
version

### ISSUE THREAD

**Issue by yulu0724** [jind11/TextFooler#33]
Hi, could you please show your python/pytorch/cuda version? I always have problems installing the requirements. Thanks!

**Comment by yulu0724** [comment]
When I use python3, I had problem installing pattern. When I changed to python2.7. I had some other issues saying it need a python3 version....

**Comment by jind11** [comment]
I used python 3..6, cuda 9.0/10.0, and pytorch 0.4.

**Comment by jind11** [comment]
Could you post your error message so that I can better help with?

**Comment by yulu0724** [comment]
Thanks for the reply.

Traceback (most recent call last):
  File "attack_classification.py", line 6, in <module>
    import criteria
  File "/home/lu.yu/TextFooler/criteria.py", line 4, in <module>
    from pattern.en import conjugate, lemma, lexeme, PRESENT, SG, PL, PAST, PROGRESSIVE
ModuleNotFoundError: No module named 'pattern'

When I tried to install the pattern. I have the issues as follows:

UnsatisfiableError: The following specifications were found to be in conflict:
  - pattern -> python=2.7
  - python=3.7
Use "conda info <package>" to see the dependencies for each package.

**Comment by yulu0724** [comment]
The problem is solved after I changed the python version to 3.6. Thanks

**Comment by jind11** [comment]
Ok, I am glad you have solved the problem. I am also surprised that the python 3.7 is not compatible here. Thanks for pointing this out.
