### ISSUE TITLE
About pytorch_pretrained_bert

### ISSUE THREAD

**Issue by lexmen318** [jind11/TextFooler#7]
Hi，
Do you consider migrating it to transformers according to the guide of Huggingface's github.

thx a lot!

**Comment by jind11** [comment]
hi, what do you mean by "migrating to transformers"? Thanks!

**Comment by lexmen318** [comment]
I found the trained BERT models are based on "pytorch_pretrained_bert", however "pytorch_pretrained_bert" has been update to "pytorch_transformers" and then to "transformers".
So I suggest you to migrate the package according to following guides:
https://github.com/huggingface/transformers#Migrating-from-pytorch-transformers-to-transformers

**Comment by jind11** [comment]
I think it is not that hard, I can finish this after my ddl on 12/9.

**Comment by lexmen318** [comment]
Thank you very much!
