### ISSUE TITLE
Doubt regarding synonym replacement

### ISSUE THREAD

**Issue by RishabhMaheshwary** [jind11/TextFooler#9]
I have doubt from the word replacement section of the paper.

1. Are you querying the target model for every synonym of a word (selected after POS and semantic similarity check) and than selecting the synonym with least confidence score, and than repeating the process for each word in the text ordered by their classification drop score ?

2. How are you calculating the no. of queries to the model ?

**Comment by jind11** [comment]
Hi, here are the answers:
1. Your understanding is all correct.
2. Every time when I need to get the probability vector from the model by feeding the input sentence, it is counted as one query. For example, testing the confidence score after replacing the target word with every single word among the synonym candidates is counted as one query.
Let me know if you have any other questions.

**Comment by RishabhMaheshwary** [comment]
So, Are you not counting the queries to the target model during word ranking step ?

**Comment by jind11** [comment]
Actually any time that involves querying the model for the probability vector, I counted it in, which includes the word ranking step.

**Comment by RishabhMaheshwary** [comment]
Ok, Thanks.
